export type MissionLevel = "BEGINNER" | "INTERMEDIATE" | "ADVANCED";

export type OrderMission = {
  id: string;
  number: string;
  level: MissionLevel;
  module: string;
  titleFa: string;
  briefFa: string;
  objectiveFa: string;
  commands: string[];
};

export const orderMissions: OrderMission[] = [
  {
    id: "first-commit",
    number: "01",
    level: "BEGINNER",
    module: "FOUNDATIONS",
    titleFa: "ساخت اولین Commit",
    briefFa: "یک پوشهٔ معمولی شامل سه فایل داری. آن را به Repository تبدیل کن و اولین Snapshot را بساز.",
    objectiveFa: "Repository باید ساخته شود، وضعیت بررسی شود و همهٔ فایل‌ها داخل اولین Commit قرار بگیرند.",
    commands: ["git init", "git status", "git add .", "git commit -m \"chore: initial commit\"", "git log --oneline"],
  },
  {
    id: "author-config",
    number: "02",
    level: "BEGINNER",
    module: "FOUNDATIONS",
    titleFa: "تنظیم هویت نویسنده",
    briefFa: "Git نصب است اما نام و ایمیل نویسنده هنوز تنظیم نشده‌اند. پیش از Commit هویت را کامل کن.",
    objectiveFa: "ابتدا تنظیمات را ثبت و بررسی کن؛ سپس Repository و Commit اول را بساز.",
    commands: ["git config --global user.name \"Your Name\"", "git config --global user.email \"you@example.com\"", "git config --list", "git init", "git add .", "git commit -m \"chore: start project\""],
  },
  {
    id: "selected-stage",
    number: "03",
    level: "BEGINNER",
    module: "LOCAL WORKFLOW",
    titleFa: "Commit انتخابی فایل‌ها",
    briefFa: "فقط تغییرهای app.js و style.css باید Commit شوند و فایل notes.txt فعلاً بیرون Commit بماند.",
    objectiveFa: "قبل و بعد از Stage وضعیت را بررسی کن و فقط دو فایل موردنظر را Commit کن.",
    commands: ["git status", "git add app.js style.css", "git diff --staged", "git commit -m \"feat: update interface\"", "git status"],
  },
  {
    id: "unstage-file",
    number: "04",
    level: "BEGINNER",
    module: "UNDO",
    titleFa: "خارج‌کردن فایل اشتباه از Stage",
    briefFa: "app.js و README.md هر دو Stage شده‌اند اما Commit فعلی فقط باید مستندات را ثبت کند.",
    objectiveFa: "تغییر app.js حفظ شود ولی از Commit مستندات بیرون بماند.",
    commands: ["git status", "git restore --staged app.js", "git diff --staged", "git commit -m \"docs: update readme\"", "git status"],
  },
  {
    id: "ignore-secret",
    number: "05",
    level: "BEGINNER",
    module: "LOCAL WORKFLOW",
    titleFa: "جلوگیری از Commit شدن Secret",
    briefFa: "فایل .env داخل پروژه دیده می‌شود و نباید وارد تاریخچه شود.",
    objectiveFa: ".env را Ignore کن و فقط .gitignore و فایل‌های امن را Commit کن.",
    commands: ["echo .env >> .gitignore", "git status", "git add .gitignore src/", "git diff --staged", "git commit -m \"chore: ignore environment file\""],
  },
  {
    id: "first-push",
    number: "06",
    level: "BEGINNER",
    module: "REMOTE & GITHUB",
    titleFa: "اولین Push به GitHub",
    briefFa: "پروژه یک Commit محلی دارد اما هنوز به GitHub متصل نیست.",
    objectiveFa: "Remote را تعریف کن، اتصال را بررسی کن و main را همراه Upstream بفرست.",
    commands: ["git remote add origin REPOSITORY_URL", "git remote -v", "git branch -M main", "git push -u origin main", "git status"],
  },
  {
    id: "clone-project",
    number: "07",
    level: "BEGINNER",
    module: "REMOTE & GITHUB",
    titleFa: "شروع کار روی پروژهٔ موجود",
    briefFa: "می‌خواهی روی Repository تیم کار کنی و ابتدا باید یک نسخهٔ محلی سالم بسازی.",
    objectiveFa: "پروژه را Clone کن، وارد پوشه شو و Remote، Branch و تاریخچه را بررسی کن.",
    commands: ["git clone REPOSITORY_URL", "cd project-name", "git remote -v", "git branch --show-current", "git log --oneline -5"],
  },
  {
    id: "feature-branch",
    number: "08",
    level: "INTERMEDIATE",
    module: "BRANCH & MERGE",
    titleFa: "توسعه روی Feature Branch",
    briefFa: "قابلیت Login نباید مستقیماً روی main توسعه داده شود.",
    objectiveFa: "Branch مستقل بساز، تغییر را Commit کن، به main برگرد و Branch را Merge کن.",
    commands: ["git switch -c feature/login", "git add src/login.js", "git commit -m \"feat: add login\"", "git switch main", "git merge feature/login", "git log --oneline --graph --all"],
  },
  {
    id: "soft-reset",
    number: "09",
    level: "INTERMEDIATE",
    module: "UNDO",
    titleFa: "اصلاح Commit ناقص",
    briefFa: "Commit آخر ناقص است و باید باز شود، فایل فراموش‌شده اضافه شود و Commit کامل‌تری ساخته شود.",
    objectiveFa: "Commit را بدون از دست‌دادن Stage باز کن و Snapshot اصلاح‌شده بساز.",
    commands: ["git log --oneline -3", "git reset --soft HEAD~1", "git add missing-file.js", "git diff --staged", "git commit -m \"feat: complete checkout flow\""],
  },
  {
    id: "safe-revert",
    number: "10",
    level: "INTERMEDIATE",
    module: "UNDO",
    titleFa: "بازگردانی امن روی Branch مشترک",
    briefFa: "یک Commit خراب قبلاً Push شده و اعضای تیم آن را دریافت کرده‌اند.",
    objectiveFa: "بدون بازنویسی تاریخچه، اثر Commit خراب را خنثی و نتیجه را منتشر کن.",
    commands: ["git pull origin main", "git log --oneline", "git revert BAD_COMMIT_HASH", "git log --oneline -3", "git push origin main"],
  },
  {
    id: "stash-context",
    number: "11",
    level: "INTERMEDIATE",
    module: "BRANCH & MERGE",
    titleFa: "تغییر Context با Stash",
    briefFa: "روی Feature تغییر ناتمام داری اما باید فوراً یک Hotfix روی main انجام دهی.",
    objectiveFa: "تغییر ناتمام را موقتاً کنار بگذار، Hotfix را Commit کن و سپس به Feature برگرد.",
    commands: ["git stash -u", "git switch main", "git switch -c hotfix/header", "git add .", "git commit -m \"fix: repair header\"", "git switch feature/current", "git stash pop"],
  },
  {
    id: "fetch-review",
    number: "12",
    level: "INTERMEDIATE",
    module: "REMOTE & GITHUB",
    titleFa: "بررسی Remote پیش از ادغام",
    briefFa: "می‌خواهی تغییرهای جدید main را ببینی اما هنوز آماده نیستی Working Tree تغییر کند.",
    objectiveFa: "ابتدا فقط اطلاعات Remote را بگیر، اختلاف را بررسی و سپس ادغام کن.",
    commands: ["git status", "git fetch origin", "git log --oneline HEAD..origin/main", "git diff HEAD..origin/main", "git merge origin/main"],
  },
  {
    id: "no-ff-merge",
    number: "13",
    level: "INTERMEDIATE",
    module: "BRANCH & MERGE",
    titleFa: "حفظ مرز Feature با Merge Commit",
    briefFa: "Feature آماده است و تیم می‌خواهد مسیر آن در گراف تاریخچه واضح باقی بماند.",
    objectiveFa: "main را به‌روز کن، Feature را با Merge Commit ادغام و Branch را پاک کن.",
    commands: ["git switch main", "git pull origin main", "git merge --no-ff feature/payment", "git push origin main", "git branch -d feature/payment"],
  },
  {
    id: "pull-request",
    number: "14",
    level: "INTERMEDIATE",
    module: "TEAMWORK",
    titleFa: "ساخت Pull Request تمیز",
    briefFa: "تغییر Feature آمادهٔ Review است و باید از Branch جداگانه روی GitHub پیشنهاد شود.",
    objectiveFa: "وضعیت را بررسی کن، Branch را Push کن و یک Pull Request بساز.",
    commands: ["git status", "git log --oneline origin/main..HEAD", "git push -u origin feature/search", "gh pr create --fill", "gh pr view --web"],
  },
  {
    id: "rebase-feature",
    number: "15",
    level: "ADVANCED",
    module: "BRANCH & MERGE",
    titleFa: "به‌روزکردن Feature با Rebase",
    briefFa: "Feature خصوصی تو از main عقب افتاده و می‌خواهی پیش از PR تاریخچه‌ای خطی بسازی.",
    objectiveFa: "main جدید را دریافت کن، Feature را روی آن Rebase و Push محافظت‌شده انجام بده.",
    commands: ["git fetch origin", "git switch feature/profile", "git rebase origin/main", "git log --oneline --graph --all", "git push --force-with-lease origin feature/profile"],
  },
  {
    id: "cherry-pick-hotfix",
    number: "16",
    level: "ADVANCED",
    module: "BRANCH & MERGE",
    titleFa: "انتقال انتخابی Hotfix",
    briefFa: "یک Fix مهم روی develop ثبت شده اما Release Branch فقط همان Commit را نیاز دارد.",
    objectiveFa: "Release را به‌روز کن، Commit مشخص را اعمال، تست و Push کن.",
    commands: ["git fetch origin", "git switch release/2.1", "git pull --ff-only origin release/2.1", "git cherry-pick HOTFIX_COMMIT", "npm test", "git push origin release/2.1"],
  },
  {
    id: "squash-feature",
    number: "17",
    level: "ADVANCED",
    module: "BRANCH & MERGE",
    titleFa: "Squash کردن Feature شلوغ",
    briefFa: "Feature شامل Commitهای آزمایشی زیادی است و main باید فقط یک Commit نهایی دریافت کند.",
    objectiveFa: "Feature را به‌صورت Squash وارد main کن، Snapshot نهایی بساز و Push کن.",
    commands: ["git switch main", "git pull origin main", "git merge --squash feature/dashboard", "git diff --staged", "git commit -m \"feat: add dashboard\"", "git push origin main"],
  },
  {
    id: "resolve-conflict",
    number: "18",
    level: "ADVANCED",
    module: "BRANCH & MERGE",
    titleFa: "حل Conflict در Merge",
    briefFa: "ادغام Feature با main متوقف شده و فایل app.js دارای Conflict Marker است.",
    objectiveFa: "فایل‌های درگیر را پیدا کن، Conflict را حل و Merge را کامل کن.",
    commands: ["git status", "git diff --name-only --diff-filter=U", "code app.js", "git add app.js", "git commit", "git log --oneline --graph --all"],
  },
  {
    id: "fork-contribution",
    number: "19",
    level: "ADVANCED",
    module: "TEAMWORK",
    titleFa: "Contribution از طریق Fork",
    briefFa: "به Repository اصلی دسترسی Write نداری و باید تغییر را از Fork شخصی پیشنهاد بدهی.",
    objectiveFa: "Upstream را تعریف کن، Branch تازه بساز، تغییر را به Fork بفرست و PR باز کن.",
    commands: ["git remote add upstream ORIGINAL_REPOSITORY_URL", "git fetch upstream", "git switch -c fix/accessibility upstream/main", "git add .", "git commit -m \"fix: improve accessibility\"", "git push -u origin fix/accessibility", "gh pr create --repo OWNER/PROJECT --fill"],
  },
  {
    id: "actions-pipeline",
    number: "20",
    level: "ADVANCED",
    module: "GITHUB ACTIONS",
    titleFa: "اضافه‌کردن Pipeline تست",
    briefFa: "پروژه باید روی هر Pull Request به‌صورت خودکار نصب، تست و Build شود.",
    objectiveFa: "Workflow را روی Branch جدا بساز، محلی بررسی کن و برای Review بفرست.",
    commands: ["git switch -c ci/github-actions", "mkdir -p .github/workflows", "code .github/workflows/ci.yml", "git add .github/workflows/ci.yml", "git commit -m \"ci: add test workflow\"", "git push -u origin ci/github-actions", "gh pr create --fill"],
  },
];
